name: tiga_belas_apps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  firebase_ui_auth: ^1.7.0
  chewie: ^1.8.1
  cloud_firestore: ^4.17.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  dartz: ^0.10.1
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.0+3
  bloc: ^8.1.4
  flutter_native_splash: ^2.4.1
  iconly: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#1835F3"
  image: "assets/images/icon_tiga_belas.png"
  android_12:
    image: "assets/images/icon_tiga_belas.png"
    icon_background_color: "#1835F3"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
