// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvEgDI7EqRj3y7R3xVbKa0Ctnh33cgHcE',
    appId: '1:555932525222:web:1bc242232d7787063c4a67',
    messagingSenderId: '555932525222',
    projectId: 'tiga-belas-edu-apps',
    authDomain: 'tiga-belas-edu-apps.firebaseapp.com',
    storageBucket: 'tiga-belas-edu-apps.appspot.com',
    measurementId: 'G-C6TSHYY0BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnnSIhaNYKCZ-HTI6Ad1yO-2h0k4JbdpY',
    appId: '1:555932525222:android:9d63ad19eed1a8833c4a67',
    messagingSenderId: '555932525222',
    projectId: 'tiga-belas-edu-apps',
    storageBucket: 'tiga-belas-edu-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzezuw28l7AFk680T9lMzDo1-Bh42Naq8',
    appId: '1:555932525222:ios:f9802775ae3a13ae3c4a67',
    messagingSenderId: '555932525222',
    projectId: 'tiga-belas-edu-apps',
    storageBucket: 'tiga-belas-edu-apps.appspot.com',
    iosBundleId: 'com.example.tigaBelasApps',
  );
}
